### ISSUE TITLE
GitLabForm throws gitlabform.gitlab.core.UnexpectedResponseException

### ISSUE THREAD

**Issue by j86989** [egnyte/gitlabform#91] opened 2020-03-10 13:32 UTC
```
+ gitlab_venv/bin/gitlabform ALL_DEFINED
>>> Processing ALL groups and projects defined in config
*** # of groups to process: 17
*** # of projects to process: 877
Traceback (most recent call last):
  File "gitlab_venv/bin/gitlabform", line 6, in <module>
    GitLabForm().main()
  File "/home/jenkins-slave/workspace/gitlab-reset-settings-for-all-groups/gitlab_venv/lib64/python3.6/site-packages/gitlabform/gitlabform/core.py", line 178, in main
    self.process_all(projects_and_groups, groups)
  File "/home/jenkins-slave/workspace/gitlab-reset-settings-for-all-groups/gitlab_venv/lib64/python3.6/site-packages/gitlabform/gitlabform/core.py", line 243, in process_all
    self.process_group_members(group, configuration)
  File "/home/jenkins-slave/workspace/gitlab-reset-settings-for-all-groups/gitlab_venv/lib64/python3.6/site-packages/gitlabform/gitlabform/core.py", line 40, in method_wrapper
    return method(self, project_and_group, configuration)
  File "/home/jenkins-slave/workspace/gitlab-reset-settings-for-all-groups/gitlab_venv/lib64/python3.6/site-packages/gitlabform/gitlabform/core.py", line 490, in process_group_members
    self.gl.add_member_to_group(group, user, access_level_to_set, expires_at_to_set)
  File "/home/jenkins-slave/workspace/gitlab-reset-settings-for-all-groups/gitlab_venv/lib64/python3.6/site-packages/gitlabform/gitlab/members.py", line 38, in add_member_to_group
    data=data, expected_codes=201)
  File "/home/jenkins-slave/workspace/gitlab-reset-settings-for-all-groups/gitlab_venv/lib64/python3.6/site-packages/gitlabform/gitlab/core.py", line 114, in _make_requests_to_api
    response = self._make_request_to_api(path_as_format_string, args, method, data, expected_codes, json)
  File "/home/jenkins-slave/workspace/gitlab-reset-settings-for-all-groups/gitlab_venv/lib64/python3.6/site-packages/gitlabform/gitlab/core.py", line 169, in _make_request_to_api
    response.status_code)
gitlabform.gitlab.core.UnexpectedResponseException: Request url='https://git.egnyte-internal.com/api/v4/groups/xops_approvers/members', method=POST, data='{'user_id': 364, 'expires_at': None, 'access_level': 30}' failed - expected code(s) [201], got code 409 & body: 'b'{"message":"Member already exists"}''

```

```
(gitlab_venv) [root@bldvs002 gitlab-reset-settings-for-all-groups]# deactivate 
[root@bldvs002 gitlab-reset-settings-for-all-groups]# source gitlab_venv/bin/activate
(gitlab_venv) [root@bldvs002 gitlab-reset-settings-for-all-groups]# pip freeze 
certifi==2019.11.28
chardet==3.0.4
emoji==0.3.9
gitlab-tools==1.7.4
gitlabform==1.14.0
idna==2.9
Jinja2==2.11.1
MarkupSafe==1.1.1
py-dateutil==2.2
python-gitlab==2.0.1
pytz==2019.3
PyYAML==5.3
requests==2.23.0
ruamel.yaml==0.15.42
sarge==0.1.5.post0
six==1.14.0
termcolor==1.1.0
urllib3==1.25.8
```

**Comment by gdubicki** [comment] 2020-03-12 19:00
Fixed in 1.14.1 which is being released right now.

What was missing is pagination support for the call to the API returning a list of group members - we were getting only first 20 of them so the code was failing on 21st when we tried to add him like he was not there already.

In the future I recommend using debug mode (`-d`) to learn more about where is the app failing.

**Comment by wokoman** [comment] 2021-01-21 21:05
Sorry for resurrecting this issue, but I started getting the very similiar error with 1.20.0 running against GitLab 13.7.1-ee.

I have simply list of users added under a group, first pass goes smoothly (gitlabform adds them to the group), but next ones does not go through, as it ends with this error.
Even removing users stops working, as if the entire block of calls to that group is dropped, when the program API call ends with 409 code.

Same issue when using CI.

I've tried adding 409 code into expected ones in the members.py file, but the behaviour became erratic (wrong users got deleted, only some users got added, etc.).

Attaching [gitlabform_log.txt](https://github.com/egnyte/gitlabform/files/5852149/gitlabform_log.txt). Any help would be greatly appreciated.

**Comment by gdubicki** [comment] 2021-01-22 08:22
Hey @wokoman , thanks for reporting the issue!

> I have simply list of users added under a group, first pass goes smoothly (gitlabform adds them to the group), but next ones does not go through, as it ends with this error.

So the output of the first run is in the gitlabform_log.txt that you attached?

If so then please also share the output of the 2nd run, the one with error.

You can either anonymise it and paste it here or share it securely only with me using this link: https://egnyte.egnyte.com/ul/qQdtvNXL35

> Even removing users stops working, as if the entire block of calls to that group is dropped, when the program API call ends with 409 code.

It would also help if you could share this output with me, but we can start with the above one and see if this is enough.

**Comment by wokoman** [comment] 2021-01-25 15:55
Thanks @gdubicki for looking into that. The text file I've posted is the second run with the error (line 40 and on).

I've tried this just to be sure:
1. Created a new group in UI, with only me as sole member
2. Tried to run GitLabForm config with me and other users as members
3. I get 409 error, because I'm already in that group. No users are added.

[Thist](https://github.com/egnyte/gitlabform/files/5867727/gitlabform_first_run.txt) is the command output after the first run. [This](https://github.com/egnyte/gitlabform/files/5867728/gitlabform_second_run_debug.txt) is the second run with -d flag.

I hope it's useful! Let me know, if I can be of any more help.

**Comment by gdubicki** [comment] 2021-01-31 21:09
This is super weird. I have reviewed the app code and I have no clue why after correctly getting the `user.one` user as one of the users before making changes (`Group members BEFORE:` log line) the app tries to add this user again (which is indicated by the `Adding user 'user.one' who previously was not a member.` log line)...

**Comment by gdubicki** [comment] 2021-01-31 21:39
I modified the test to setup a config and then ru-run the setup and tested on the same GitLab version as yours and I cannot reproduce it: :(

```
Reading config from provided string.
url = http://localhost/api/v4/version , method = GET , data = null, json = null
Starting new HTTP connection (1): localhost:80
http://localhost:80 "GET /api/v4/version HTTP/1.1" 200 48
response code=200
response json={"revision": "d49cd5e5165", "version": "13.7.1-ee"}
Connected to GitLab version: 13.7.1-ee (d49cd5e5165)
Reading config from provided string.
url = http://localhost/api/v4/groups/gitlabform_tests_group/projects?include_subgroups=true&per_page=100 , method = GET , data = null, json = null
http://localhost:80 "GET /api/v4/groups/gitlabform_tests_group/projects?include_subgroups=true&per_page=100 HTTP/1.1" 200 2
response code=200
response json=[]
*** # of groups to process: 1
*** # of projects to process: 0
Group config: {'enforce_group_members': True, 'group_members': {'root': {'access_level': 50}, 'group_member_user2': {'access_level': 30}, 'group_member_user3': {'access_level': 40}}}
Common config: {}
> (1/1) Processing: gitlabform_tests_group
Skipping group_secret_variables - not in config.
Skipping group_settings - not in config.
Processing group_members
url = http://localhost/api/v4/groups/gitlabform_tests_group/members?per_page=100 , method = GET , data = null, json = null
http://localhost:80 "GET /api/v4/groups/gitlabform_tests_group/members?per_page=100 HTTP/1.1" 200 None
response code=200
response json=[{"access_level": 50, "avatar_url": "https://www.gravatar.com/avatar/e64c7d89f26bd1972efa854d13d7dd61?s=80&d=identicon", "created_at": "2021-01-31T21:29:26.415Z", "expires_at": null, "id": 1, "name": "Administrator", "state": "active", "username": "root", "web_url": "http://gitlab.foobar.com/root"}, {"access_level": 40, "avatar_url": "https://www.gravatar.com/avatar/3c53e776f47721911be5d5d39e20be92?s=80&d=identicon", "created_at": "2021-01-31T21:29:31.296Z", "expires_at": null, "id": 4, "name": "group_member_user3 Example", "state": "active", "username": "group_member_user3", "web_url": "http://gitlab.foobar.com/group_member_user3"}, {"access_level": 30, "avatar_url": "https://www.gravatar.com/avatar/c297e97d540541888a0257fbe75b2f94?s=80&d=identicon", "created_at": "2021-01-31T21:29:31.509Z", "expires_at": null, "id": 3, "name": "group_member_user2 Example", "state": "active", "username": "group_member_user2", "web_url": "http://gitlab.foobar.com/group_member_user2"}]
Group members BEFORE: [{'id': 1, 'name': 'Administrator', 'username': 'root', 'state': 'active', 'avatar_url': 'https://www.gravatar.com/avatar/e64c7d89f26bd1972efa854d13d7dd61?s=80&d=identicon', 'web_url': 'http://gitlab.foobar.com/root', 'access_level': 50, 'created_at': '2021-01-31T21:29:26.415Z', 'expires_at': None}, {'id': 4, 'name': 'group_member_user3 Example', 'username': 'group_member_user3', 'state': 'active', 'avatar_url': 'https://www.gravatar.com/avatar/3c53e776f47721911be5d5d39e20be92?s=80&d=identicon', 'web_url': 'http://gitlab.foobar.com/group_member_user3', 'access_level': 40, 'created_at': '2021-01-31T21:29:31.296Z', 'expires_at': None}, {'id': 3, 'name': 'group_member_user2 Example', 'username': 'group_member_user2', 'state': 'active', 'avatar_url': 'https://www.gravatar.com/avatar/c297e97d540541888a0257fbe75b2f94?s=80&d=identicon', 'web_url': 'http://gitlab.foobar.com/group_member_user2', 'access_level': 30, 'created_at': '2021-01-31T21:29:31.509Z', 'expires_at': None}]
Nothing to change for user 'root' - same config now as to set.
Nothing to change for user 'group_member_user3' - same config now as to set.
Nothing to change for user 'group_member_user2' - same config now as to set.
(...)
```

**Comment by wokoman** [comment] 2021-02-07 21:06
Hey Greg, tried it on different instance of GitLab, and it seems to work just fine. But even if I wipe my installation clean, same issue. But I guess there must be something in my environment messing with the API calls or whatnot.
Thanks for looking into this, and sorry for _crying wolf_, eh? Cheers!

**Comment by gdubicki** [comment] 2021-02-08 06:53
Hey @wokoman , thanks for the update.

One last thing that comes to my mind - in case want to troubleshoot it more - is that it looks like something you are running more than 1 instance of GitLabForm at a time. Are you sure this is not happening? Note that system hooks may trigger more than once per event and that GitLab CI doesn’t limit parallel pipeline runs by default.

**Comment by wokoman** [comment] 2021-02-08 07:34
Not to my knowledge. I run simply single GitLabForm command against single GitLab instance in Minikube.
I was getting REST API inconsistency with Terraform too, when I had to run it multiple times (like 5-10 times even), because the Terraform couldn't get a lock on the state file stored in GitLab. So there was definitely something off with the GitLab's API, but couldn't pinpoint what was it.
I switched to really simple docker-compose, and suddenly both tools seem to work as they should 🤷

**Comment by gdubicki** [comment] 2021-02-08 09:46
So GitLabForm is among these 2 tools and now is working fine for you?

**Comment by wokoman** [comment] 2021-02-08 10:12
Yep, I used GitLabForm and Terraform on the same GitLab instance, and both weren't working consistently, but now on a fresh GitLab installation (that's not on Minikube), they're working just fine.

**Comment by gdubicki** [comment] 2021-05-15 10:33
I am closing this issue as I assume your issue is fixed, @wokoman. Please reopen if it is not.

**Closed by gdubicki** 2021-05-15 10:33 UTC
Labels: 🐛bug
