### ISSUE TITLE
How to configure existing private deployment key

### ISSUE THREAD

**Issue by vchepkov** [egnyte/gitlabform#305] opened 2021-11-10 19:14 UTC
Hi,

I am trying to set the same private deployment key already configured in in gitlab
If I add it to gitlabform config _deploy_keys_ stanza, I get a failure -

```
failed - expected code(s) [201], got code 400 & body: '{"message":{"deploy_key.fingerprint":["has already been taken"]}}'
```

when I do it in the GUI, I just 'enable' an existing key. Is it possible to do the same with gitlabform?

Thanks,
Vadym

**Comment by gdubicki** [comment] 2021-11-10 20:08
Duplicate of #19. Can you please upvote that issue, @vchepkov ? Closing this one.

**Closed by gdubicki** 2021-11-10 20:08 UTC
