### ISSUE TITLE
using enforce_group_members on sub-groups results in crash

### ISSUE THREAD

**Issue by FlorianLudwig** [egnyte/gitlabform#179] opened 2021-02-19 08:41 UTC
having:

```yaml
  "group":
    group_members: ...
    enforce_group_members: true

  "group/sub":
    group_members: ...
    enforce_group_members: true
```

results in:

```
  File "gitlabform/configuration/projects_and_groups.py", line 112, in merge_configs
    merged_config[key] = {
TypeError: 'bool' object is not a mapping
```

tested with gitlabform `1.20.2`

**Comment by gdubicki** [comment] 2021-06-06 20:26
Hi @FlorianLudwig !

Can you please upgrade to the current latest version in v2.x line and try again? The code for generating the effective config has changed a lot since v1 and they may already be fixed.

**Comment by gdubicki** [comment] 2021-06-07 17:20
I was not able to reproduce it in a test - see the commit above - so I am closing this. Please reopen if you are still seeing the issue after upgrading GitLabForm to v2+.

**Closed by gdubicki** 2021-06-07 17:20 UTC
Labels: 🐛bug

**Comment by FlorianLudwig** [comment] 2021-06-18 14:52
yes, looks good with v2, thanks
