### ISSUE TITLE
Re-running gitlabform with changes to jira services doesn't apply any change

### ISSUE THREAD

**Issue by Dridge** [egnyte/gitlabform#69] opened 2019-12-11 10:26 UTC
I have noticed that the password variable set in the repo CI/CD variables can't be used in the config.yml, but even when I make changes to my JIRA service settings in the config.yml the jira service remains unchanged. Do you need to manually delete the settings? Or can they be deleted before being re-applied with new settings?

Generally struggling with getting these services set up correctly. I have to replace the password below in order to avoid leaving the password in the config.yml, and replace it at the gitlab-ci.yml level with: `sed -i -e 's/SED_REPLACE_JIRA_PASSWORD/'"$JIRA_PASSWORD"'/g' config.yml`.

My services configuration, changing the password doesn't seem to get applied, nor does changes to the commit events from true to false.

>     "group/subgroup/projectname":
>       services:
>           mattermost:
>               active: true
>               webhook: https://mattermost.com/hooks/xx9bnr7jijndtgangda64w
>               username: gitlab
>               merge_requests_events: true
>               merge_request_channel: "merge-requests-channel"
>               push_events: false
>               issues_events: false
>               confidential_issues_events: false
>               tag_push_events: false
>               note_events: false
>               confidential_note_events: false
>               pipeline_events: false
>               wiki_page_events: false
>               branches_to_be_notified: "all"
>           jira:
>               active: true
>               url: http://jiralo.xxx.com
>               username: "botaccess"
>               password: "SED_REPLACE_JIRA_PASSWORD"
>               merge_requests_events: true
>               commit_events: true

**Comment by gdubicki** [comment] 2019-12-18 06:54
Hi @Dridge !

gitlabform just goes through each service defined in this config sections and makes PUT requests to GitLab API. So both password change and commit events change flag flip should work.

But I have checked that and it seems that there is a bug in GitLab API that makes those PUT requests not work, at least for JIRA service.

We could try a workaround of deleting and recreating services with API on each gitlabform run but I am afaid of the side effects (and a bit about performance). I have quickly tried making a diff between current and target service config (or, to be precise, a check for target config being subset of the current config) to check if a PUT request is needed but for example for Jira service the GitLab API does not return password in response (which make sense, of course) what makes this diffing ineffective. Maybe we should make this "always recreate services" a default off feature (or rather a workaround)?

**Comment by Dridge** [comment] 2019-12-20 10:28
> Maybe we should make this "always recreate services" a default off feature

This sounds reasonable to me, and the only way to get around the gitlab api bug.

**Comment by gdubicki** [comment] 2020-01-06 09:34
My new integrations tests (see link above) confirm that there is this problem, most probably with all services (I tested using the first one alphabetically, `asana`).

**Comment by gdubicki** [comment] 2020-03-07 11:20
I noted in https://gitlab.com/gitlab-org/gitlab/-/issues/202216 that the password field is not being updated too.

**Comment by gdubicki** [comment] 2020-03-08 09:44
I have just released v1.13.4 with the "recreate" flag mentioned a few comments above.

See this example config section for info how to use it: https://github.com/egnyte/gitlabform/blob/master/config.yml#L179-L183

Please let me know if this helps, @Dridge .

**Comment by gdubicki** [comment] 2020-03-09 20:15
Thanks to [Vincent Bisserié's help](https://gitlab.com/gitlab-org/gitlab/-/issues/202216#note_301934216) (if you are reading this - thank you!) I fixed the root cause and released v1.13.5 where this issue should be completely resolved without any workarounds.

Please reopen this issue if it does not help you, @Dridge .

**Closed by gdubicki** 2020-03-09 20:15 UTC
Labels: gitlab issue
