### ISSUE TITLE
Issue with unprotect_branch_new_api

### ISSUE THREAD

**Issue by bethmal** [egnyte/gitlabform#219] opened 2021-05-24 06:11 UTC
Hi,
In version 2.0.0post1, 
1. Procedure _make_requests_to_api, core.py line 113: exception when response.status_code is 404, exception message "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)".

2. Procedure _make_request_to_api, core.py line 208,: exception when response.status_code is 404, exception message "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)".

Seems expected_codes contains code 404, not quite understand why the judgement in line 192 of core.py is presented.

            if response.status_code == 404:
                raise NotFoundException("Resource path='%s' not found!" % url)

3. In branch_protector.py line 53, exception when response has no "unprotect_access_levels". 

Thanks.

**Comment by gdubicki** [comment] 2021-05-24 16:44
Hi @bethmal !

Thanks for reporting the issues.

It would help if you could provide some more context though. Preferably configuration snippets that have caused those errors.

Ad 3: can you take a loot a this please, @YuraBeznos ? Maybe it will be obvious to you what is the cause.

**Comment by bethmal** [comment] 2021-05-25 01:58
@gdubicki 
Please find below configuration snippets. Basically the case is like:

If unprotect_access_level is not provided in configuration yml file, and meanwhile master branch is not protected (the reason could be either it was not protected on purpose or is was unprotected by gitlabform ), then procedure protect_branch does nothing. In this scenario, if a file need to be updated as well, the re-protect operation fails after the file is pushed.  

If master branch is not protected (the reason could be either it was not protected on purpose or is was unprotected by gitlabform ), and then unprotect_branch_new_api is invoked somehow, exceptions mentioned above would be raised. The response code 404 is not json dump-able or loadable.

The response of get_branch_access_levels contains no unprotect_access_levels in our case.

    projects_and_groups:
      "gitlabform_test/*":
        branches:
          # see comment above - this branch config will be ADDED to the branches configured on a group level
          master:
            protected: true
            push_access_level: 40
            merge_access_level: 40
            unprotect_access_level: 40
    
        files:
          ".gitlab/merge_request_templates/MR.md":
            overwrite: true
            branches:
              - master
            skip_ci: true
            file: MR.md

**Comment by gdubicki** [comment] 2021-05-29 07:55
> If unprotect_access_level is not provided in configuration yml file, and meanwhile master branch is not protected (the reason could be either it was not protected on purpose or is was unprotected by gitlabform ), then procedure protect_branch does nothing. In this scenario, if a file need to be updated as well, the re-protect operation fails after the file is pushed.

This is fixed in main branch. Now to the second case..

**Comment by bethmal** [comment] 2021-06-04 03:29
Hi @gdubicki ,
Could 404 exception issues (protect unprotected branch) be solved as early as possible? This issue is blocking gitlabform critical feature.
Thanks.

**Comment by gdubicki** [comment] 2021-06-05 12:34
Sorry @bethmal, but we need more contributors to get issues fixed faster. I am already doing the best I can.

Please check out v2.0.2 - it should have all your issues fixed.

**Comment by gdubicki** [comment] 2021-06-08 09:20
Please check out v2.0.5rc1, @bethmal .

**Comment by bethmal** [comment] 2021-06-09 01:39
@gdubicki Thanks for the update. v2.0.5rc2 works perfect for this scenario.

**Comment by gdubicki** [comment] 2021-06-09 08:09
Great! I just released v2.0.5 final with this fix then so we can close this issue. Of course please reopen if you see any issues with this again.

**Closed by gdubicki** 2021-06-09 08:09 UTC
Labels: 🐛bug
